# Generated by Django 5.2.13 on 2026-04-17 14:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_basket_options_alter_basket_item_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)], verbose_name='Индекс')),
                ('region', models.CharField(choices=[('Brest', 'Брестская'), ('Vitebsk', 'Витебская'), ('Gomel', 'Гомельская'), ('Grogno', 'Гродненская'), ('Minsk', 'Минская'), ('Mogilev', 'Могилёвская')], max_length=15, verbose_name='Область')),
                ('district', models.CharField(max_length=100, verbose_name='Район')),
                ('city', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(regex='^[А-Яа-яЁё\\s\\-\\.]{2,100}$')], verbose_name='Населённый пункт')),
                ('street', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(regex='^[А-Яа-яЁё\\s\\-\\.]{2,100}$')], verbose_name='Улица')),
                ('building', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Дом')),
                ('housing', models.CharField(max_length=5, null=True, verbose_name='Корпус')),
                ('apartment', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Квартира/Офис')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
    ]
