# Generated by Django 5.2.13 on 2026-04-24 18:26

import django.db.models.deletion
import shop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_notification_options_alter_notification_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='housing',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Корпус'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('failed', 'Ошибка оплаты'), ('refunded', 'Возврат средств')], max_length=20, verbose_name='Статус оплаты')),
                ('payment_method', models.CharField(choices=[('card_online', 'Картой онлайн'), ('cash_on_delivery', 'Наличными при получении'), ('card_on_delivery', 'Картой при получении')], max_length=30, verbose_name='Способ оплаты')),
                ('order_status', models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтверждён'), ('assembling', 'Сборка / Настройка'), ('ready', 'Готов к отправке'), ('sent', 'В доставке'), ('delivered', 'Доставлен'), ('completed', 'Завершён'), ('canceled', 'Отменён'), ('returned', 'Возврат')], max_length=30, verbose_name='Статус заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая стоимость')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Orders', to='shop.employee', verbose_name='Курьер')),
                ('user', models.ForeignKey(default=shop.models.get_sentinel_user, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
