# Generated by Django 5.2.13 on 2026-04-25 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_support_ticket_support_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='support_ticket',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Тикет', 'verbose_name_plural': 'Тикеты'},
        ),
    ]
