# Generated by Django 5.2.13 on 2026-04-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_employee_user_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=16, unique=True, verbose_name='Номер телефона'),
        ),
    ]
