# Generated by Django 5.2.13 on 2026-04-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='media/products/', verbose_name='Путь к файлу'),
        ),
    ]
