# Generated by Django 5.2.14 on 2026-05-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('moderator', 'Модератор'), ('courier', 'Курьер'), ('admin', 'Администратор')], max_length=20, verbose_name='Должность'),
        ),
    ]
