# Generated by Django 5.2.14 on 2026-05-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=22, unique=True, verbose_name='Номер телефона'),
        ),
    ]
