# Generated by Django 5.2.14 on 2026-05-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_v2_changes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket_item',
            name='discount_notified',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_blocked',
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='media/products/', verbose_name='Путь к файлу'),
        ),
    ]
